version: "3"
services:
  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo-express-webapp-network
  mongo-express:
    image: mongo-express
    ports:
      - "3000:8081"
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - mongo-express-webapp-network

networks:
  mongo-express-webapp-network:
    driver: bridge
